const assetFiles = import.meta.glob('../assets/*.asset.json', { eager: true, import: 'default' });
export const photos = Array.from({ length: 20 }, (_, i) => assetFiles[`../assets/photo-${String(i).padStart(2, '0')}.jpg.asset.json`]?.url).filter(Boolean);
export const categories = ['All', 'Fruits', 'Vegetables', 'Fresh Produce', 'Crops', 'Bulk / Wholesale'];
export const galleryCategories = ['All', 'Farms', 'Fresh Produce', 'Harvest', 'Agriculture', 'Products', 'Supply'];
export const steps = [['Source', 'Identify and source suitable agricultural products.'], ['Select', 'Focus on quality and freshness.'], ['Prepare', 'Prepare products thoughtfully for supply.'], ['Supply', 'A dependable agricultural product experience.'], ['Build Relationships', 'Focus on lasting customer relationships.']];
export const initialData = {
 settings: { businessName: 'PLANTERRA BY AGRI ALL FARM FRESH', phone: '9323477909', address: 'FL 103, BRAMHA MAJESTIC, BLDG B4 SN 15/1-2 NIBM, Khondhwa KH, Pune, Pune City, Maharashtra, India, 411048', heroHeading: 'Fresh From Agriculture. Trusted for Quality.', heroDescription: 'PLANTERRA BY AGRI ALL FARM FRESH brings together freshness, quality and reliable agricultural supply with a commitment to better farm-to-market connections.', ctaText: 'Explore Our Products', footerText: 'Rooted in agriculture. Connected by trust.' },
 about: { introduction: 'Rooted in Agriculture. Driven by Quality.', description: 'PLANTERRA BY AGRI ALL FARM FRESH is focused on creating a dependable connection between agricultural produce, quality sourcing and customers looking for fresh and reliable farm products.', owner: 'SHAMRAO WAGHMODE', location: 'Pune, Maharashtra', focus: 'Farm Fresh & Agricultural Products' },
 products: [ ['Fresh Vegetables','Vegetables',5,'A colourful selection of vegetables with freshness at the heart.'], ['Fresh Fruits','Fruits',2,'Naturally fresh fruits, selected with care.'], ['Seasonal Produce','Fresh Produce',4,'The best of the season, straight from agricultural roots.'], ['Green Leafy Vegetables','Vegetables',10,'Fresh greens for everyday needs and business supply.'], ['Farm Fresh Crops','Crops',7,'Field-grown crops with a quality-first approach.'], ['Agricultural Produce','Crops',6,'A considered collection of agricultural essentials.'], ['Premium Fresh Produce','Fresh Produce',3,'Carefully selected produce, beautifully fresh.'], ['Bulk Agro Products','Bulk / Wholesale',18,'Agricultural produce for retail and wholesale requirements.'] ].map(([name,category,i,description],i2)=>({id:`p${i2}`,name,category,image:photos[i],description,active:true})),
 gallery: [ [8,'Farms','Rows of possibility'],[3,'Fresh Produce','A naturally colourful harvest'],[4,'Harvest','Freshly picked strawberries'],[7,'Agriculture','Golden crop close-up'],[5,'Products','Vegetables in season'],[18,'Supply','Fresh produce at the market'],[0,'Farms','Sunrise across the fields'],[2,'Fresh Produce','Fresh fruit collection'],[10,'Harvest','Growing with care'],[11,'Agriculture','New beginnings'],[16,'Products','Farm-grown potatoes'],[19,'Products','Fresh corn harvest'],[17,'Fresh Produce','Rooted in freshness'],[6,'Supply','Agricultural grain selection'],[12,'Products','Produce of the land'],[15,'Fresh Produce','Seasonal fruit selection'] ].map(([i,category,caption],j)=>({id:`g${j}`,image:photos[i],category,caption,active:true})),
 focus: [ ['Farm Fresh Products','Fresh agricultural produce sourced with a focus on quality and freshness.',5],['Quality Sourcing','Responsible sourcing and selection of agricultural products.',4],['Reliable Supply','Focused on dependable product availability and supply.',18],['Agricultural Products','A growing portfolio of farm and agro-related products.',6],['Freshness First','Keeping freshness at the centre of the customer experience.',2],['Customer Satisfaction','Building reliable and long-term customer relationships.',8] ].map(([name,description,i],j)=>({id:`f${j}`,name,description,image:photos[i],active:true})),
 testimonials: [ ['Local Business Customer','Professional presentation and a strong focus on fresh agricultural products.'],['Retail Partner','A thoughtful, freshness-first approach to agricultural supply.'],['Agriculture Buyer','Quality and dependable relationships are at the heart of the presentation.'] ].map(([name,quote],i)=>({id:`t${i}`,name,quote,active:true})),
 enquiries: [{id:'e1',name:'Demo Retail Buyer',phone:'—',email:'—',requirement:'Fresh Vegetables',message:'Demo enquiry for the portfolio.',date:'2026-10-08',status:'New'}, {id:'e2',name:'Demo Wholesale Partner',phone:'—',email:'—',requirement:'Bulk / Wholesale',message:'Sample supply enquiry.',date:'2026-10-07',status:'Contacted'}]
};
