import { useEffect, useRef, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { photos } from './data';
export function Button({variant='primary',className='',...props}){return <button className={`button button-${variant} ${className}`} {...props}/>;}
export function Arrow(){return <span aria-hidden="true">↗</span>;}
export function Image({src,alt,className='',...props}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);return <img src={failed?photos[8]:src||photos[8]} alt={alt} className={className} onError={()=>setFailed(true)} loading="lazy" {...props}/>;}
export function Logo(){return <Link to="/" className="logo"><svg viewBox="0 0 40 44" aria-hidden="true"><path d="M20 41V15M20 29C5 29 3 16 4 7c12 0 17 8 16 22ZM21 22C21 8 29 3 37 3c1 11-5 19-16 19Z" fill="none" stroke="currentColor" strokeWidth="2"/></svg><span>PLANTERRA<small>BY AGRI ALL FARM FRESH</small></span></Link>;}
export function Modal({title,onClose,children,wide=false}){const ref=useRef(null);useEffect(()=>{const previous=document.activeElement;const handler=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=ref.current?.querySelectorAll('button,input,textarea,select,a[href]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handler);const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=old;previous?.focus();};},[onClose]);return <div className="modal-backdrop" onClick={onClose}><section role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref} className={`modal ${wide?'modal-wide':''}`} onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><Button variant="ghost" aria-label="Close dialog" onClick={onClose}>×</Button></div>{children}</section></div>;}
export function Empty({text}){return <div className="empty">{text}</div>;}
export function PageIntro({eyebrow,title,description}){return <section className="page-intro"><div className="container"><p className="eyebrow">{eyebrow||'PLANTERRA / FARM FRESH'}</p><h1>{title}</h1>{description&&<p className="intro-description">{description}</p>}</div></section>;}
